### ISSUE TITLE
ImageNet-5k data

### ISSUE THREAD

**Issue by huangzehao** [cypw/DPNs#19]
Hi, yunpeng. I am trying to prepare ImageNet-5k training data by your provided train.lst.
I have prepared the ImageNet-10k, and I found that many images which in your train.lst are not included in ImageNet-10k dataset.
Such as: 
IOError: [Errno 2] No such file or directory: '/home/datasets/Dataset/imagenet10k/n02399000/n02399000_5702.JPEG'

Would you mind sharing more informations about the preparation of ImageNet-5k data?

**Comment by cypw** [comment]
Thanks for the feedback.

Maybe, I've used the "ImageNet Fall 2011 release" dataset rather than "ImageNet10K from Deng et al. ECCV2010". I'm sorry, but I cannot give you a clear answer since I've already deleted the raw dataset.

Now, I'm downloading the "ImageNet Fall 2011 release" dataset and will let you know once it is downloaded.

**Comment by cypw** [comment]
Hi @huangzehao ,

Could you please use the ImageNet API to download the missing categories? I currently do not have enough free disk space to download the full dataset to verify which one did I used.

ImageNet HTTP protocol for downloading specific category (wnid):
http://www.image-net.org/download/synset?wnid=[wnid]&username=[username]&accesskey=[accesskey]&release=latest&src=stanford

example: http://www.image-net.org/download/synset?wnid=n02399000&username=[username]&accesskey=[accesskey]&release=latest&src=stanford

**Comment by huangzehao** [comment]
Hi, @cypw , thanks for your advice.
I will have a try.

**Comment by huangzehao** [comment]
Hi, @cypw, "ImageNet Fall 2011 release" works good for me. Thanks!
